name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        go: [1.13]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Install Dependencies
      run: |
        sudo apt-get install libnl-3-dev libnl-genl-3-dev
        PROTOC_VER=3.7.1
        PROTOC_ZIP=protoc-${PROTOC_VER}-linux-x86_64.zip
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/${PROTOC_ZIP}
        sudo unzip ${PROTOC_ZIP} -d /usr/local
        rm ${PROTOC_ZIP}
    - name: Protobuf
      run: |
        make proto
        git status --porcelain
        git diff --exit-code
    - name: Build
      run: |
        go build ./...
    - name: Test
      run: |
        go test -cover -race ./...
    - name: Binaries
      run: |
        go build ./binaries/seesaw_cli
        go build ./binaries/seesaw_ecu
        go build ./binaries/seesaw_engine
        go build ./binaries/seesaw_ha
        go build ./binaries/seesaw_healthcheck
        go build ./binaries/seesaw_ncc
        go build ./binaries/seesaw_watchdog
        tar czf seesaw-linux-amd64.tar.gz seesaw_*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        overwrite: true
        file_glob: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: seesaw-linux-amd64.tar.gz
        asset_name: ${{ matrix.os }}
        tag: ${{ github.ref }}
